[workspace]
members  = ["ic_vetkeys_manager_canister"]
resolver = "2" 

[workspace.package]          
edition       = "2021"
version       = "0.1.0"
license       = "Apache-2.0"
authors       = ["Você <you@example.com>"]
description   = "Standalone demo for ic_vetkeys_manager_canister"
documentation = "https://docs.rs/ic-vetkeys"
